In [3]:
import numpy as np

In [4]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
revers_vetor = vector[::-1]
print(revers_vetor)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
A = np.random.random((5,5))
print(A)


[[0.51377552 0.81464074 0.15423594 0.48714546 0.27848214]
 [0.35096783 0.29213805 0.27357653 0.98285125 0.7501323 ]
 [0.17079012 0.2541283  0.22531082 0.87947107 0.10893749]
 [0.75257036 0.85675912 0.3862844  0.53620782 0.41734871]
 [0.01703728 0.20927745 0.28348515 0.53733639 0.50114063]]


In [8]:
mas = np.array([x for x in range(27)])
mas_3 = mas.reshape(3,3,3)
print(mas_3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [10]:
mas = np.array([3.5,1.9])
mas_int = mas.astype(int)
print(mas_int)


[3 1]


In [15]:
mas = np.array([0,1])
mas_bool = mas.astype(bool)
print(mas_bool)

[False  True]


In [22]:
mas_1 = np.array([[3,1],[6,4]])
mas_2 = np.array([[9,8],[7,2]])
mas_hstack = np.hstack((mas_1,mas_2))
print(mas_hstack)

[[3 1 9 8]
 [6 4 7 2]]


In [25]:
mas_1 = np.array([[3,1],[6,4]])
mas_2 = np.array([[9,8],[7,2]])
mas_vstack = np.vstack((mas_1,mas_2))
print(mas_vstack)

[[3 1]
 [6 4]
 [9 8]
 [7 2]]


In [30]:
mas_1 = np.array([1,2,3,4,5])
mas_2 = np.array([1,3,2,4,5])
mas_where = np.where(mas_1==mas_2)
print(mas_where)

(array([0, 3, 4], dtype=int64),)


In [31]:
mas_1 = np.array([1,2,3,4,5])
mas_2 = np.array([1,3,2,4,5])
mas_dot = np.dot(mas_1,mas_2)
print(mas_dot)

54


In [34]:
mas_1 = np.array([[3,1],[6,4]])

mas_T = mas_1.T
print(mas_T)


[[3 6]
 [1 4]]


In [36]:
mas =  np.random.random(size = [10])
mas_sort = np.sort(mas)
print(mas_sort)

[0.16483053 0.21464917 0.408623   0.51945514 0.65013019 0.72936634
 0.74186109 0.82476832 0.85225965 0.98801819]


In [40]:
mas_1 = np.array([1,2,3,4,5])
mas_2 = np.array([1,3,2,4,5])
mas_3 = np.array([1,2,3,4,5])
mas = np.array_equal(mas_1, mas_2)
print(mas)
mas_0 = np.array_equal(mas_1, mas_3)
print(mas_0)


False
True


In [45]:
mas =  np.random.random(10)
print(mas)
mas[mas.argmax()]= 0
print(mas)

[0.45139463 0.03771337 0.40945043 0.0259074  0.39537811 0.60451827
 0.51759966 0.48899549 0.7956318  0.00243408]
[0.45139463 0.03771337 0.40945043 0.0259074  0.39537811 0.60451827
 0.51759966 0.48899549 0.         0.00243408]


In [49]:
mas_1 = np.array([1,2,3,4,5])
mas_1[mas_1 % 2 == 1] = -1
print(mas_1)

[-1  2 -1  4 -1]


In [53]:
mas_1 = np.array([1,2,3,7,54])
mas_1[(mas_1 > 30) | (mas_1 < 5) ] = 10
print(mas_1)

[10 10 10  7 10]


In [63]:
mas = np.array([[3,1],[6,4],[6,4]])
mas_sort = np.sort(mas, axis=0)
print(mas_sort)


[[3 1]
 [6 4]
 [6 4]]
